// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY_1hFhRGA00cdcqU9rtzVkTfWQmuLVNo',
    appId: '1:779711771887:web:11852f2e9e8fe780c6971a',
    messagingSenderId: '779711771887',
    projectId: 'flutter-firebase-auth-4e924',
    authDomain: 'flutter-firebase-auth-4e924.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-4e924.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3VoA1xU6zw2GcJvft7G5Eq8j8jMO9yE',
    appId: '1:779711771887:android:0db2f7d2a746b5d2c6971a',
    messagingSenderId: '779711771887',
    projectId: 'flutter-firebase-auth-4e924',
    storageBucket: 'flutter-firebase-auth-4e924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGXzJHyBTwIL-LnUI7UB1OGIMBBZqMsM',
    appId: '1:779711771887:ios:3dabebae5ff7796cc6971a',
    messagingSenderId: '779711771887',
    projectId: 'flutter-firebase-auth-4e924',
    storageBucket: 'flutter-firebase-auth-4e924.appspot.com',
    iosClientId: '779711771887-ho2bmout38eh4lhcp6jeikij82gt5mhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
